/**
 * 플랫폼 관리자 메뉴명·문구 커스텀
 * - 이 파일은 공유 상수/헬퍼만 제공한다.
 * - 클라이언트에서도 import되므로 브라우저 안전 코드를 유지한다.
 * - DB 접근은 `lib/admin-copy-server.ts`에서만 처리한다.
 * - 키 네이밍·공용/전용 기준·통합 이력: `docs/ADMIN_COPY_KEY_REGISTRY.md`
 */

/** 편집 가능한 메뉴/문구 키와 기본값 (라벨 설정 페이지에서 표시 순서·그룹용) */
export const DEFAULT_ADMIN_COPY: Record<string, string> = {
  // 사이드 메뉴
  "menu.home": "메인으로",
  "menu.dashboard": "대시보드",
  "menu.tournaments": "대회관리",
  "menu.participants": "참가자관리",
  "menu.brackets": "대진표관리",
  "menu.members": "회원관리",
  "menu.inquiries": "문의관리",
  "menu.venues": "클라이언트 관리",
  "menu.venueList": "클라이언트 목록",
  "menu.clientApplications": "클라이언트 신규신청",
  "menu.settings": "설정",
  // 상단 유저 메뉴
  "nav.myInfo": "내 정보",
  "nav.settings": "설정",
  "nav.home": "메인으로",
  "nav.logout": "로그아웃",
  // 공통
  "app.title": "CAROM.CLUB 관리자",
  "footer.copyright": "CAROM.CLUB 관리자",
  // 설정 메뉴
  "settings.menu.site": "사이트 설정",
  "settings.menu.notifications": "알림 설정",
  "settings.menu.integration": "연동 설정",
  "settings.menu.labels": "메뉴/문구",

  // ----- 사이트 안내/설명 (메인·대회·당구장·커뮤니티 등) -----
  "site.home.tournaments.title": "진행중 대회",
  "site.home.tournaments.subtitle": "참가 신청 가능한 대회를 확인하세요.",
  "site.home.tournaments.subtitleEmpty": "곧 새로운 대회가 올라올 예정입니다.",
  "site.home.tournaments.empty": "등록된 대회가 없습니다.",
  "site.home.tournaments.btnList": "대회 목록 보기",
  "site.home.tournaments.btnViewAll": "전체보기 →",
  "site.home.tournaments.btnJoin": "참가하기",
  "site.home.tournaments.nearbyLoading": "위치 확인 중…",
  "site.home.tournaments.nearbyFind": "내 주변 대회 찾기",
  "site.home.tournaments.nearbyErrorGeolocation": "이 기기에서는 위치를 사용할 수 없습니다.",
  "site.home.tournaments.nearbyErrorFetch": "목록을 불러오지 못했습니다.",
  "site.home.tournaments.nearbyErrorPermission": "위치 권한이 필요합니다. 버튼을 다시 누르고 허용해 주세요.",
  "site.home.venues.title": "당구장 소개",
  "site.home.venues.subtitle": "제휴 당구장을 소개합니다.",
  "site.home.venues.subtitleWithList": "대표 구장을 만나보세요.",
  "site.home.venues.empty": "등록된 당구장이 없습니다.",
  /** venueLink 슬롯 자동 모드 단일 링크 문구 */
  "site.home.venues.linkVenueListCta": "당구장 전체 보기 →",
  "site.home.venues.manualTitleFallback": "제목 없음",
  "site.home.venues.emptyFiltered": "해당 구분의 당구장이 없습니다. ({label})",
  "site.home.venues.filterAria": "당구장 구분",
  "site.home.venues.categoryAll": "전체",
  "site.home.venues.categoryDaedae": "대대전용",
  "site.home.venues.categoryMixed": "복합구장",
  "site.home.venues.carouselPrev": "이전",
  "site.home.venues.carouselNext": "다음",
  /** `{n}` → 페이지 번호 (캐러셀 도트·접근성) */
  "site.home.venues.carouselPageAria": "{n}페이지",
  "site.home.venues.btnViewAll": "전체 보기 →",
  "site.home.community.notes.title": "난구노트",
  "site.home.community.notes.desc": "연습·경기 기록을 남기고 언제든 복기해 보세요.",
  "site.home.community.nangu.title": "난구해결사",
  "site.home.community.nangu.desc": "문제구 질문 및 해법 토론 게시판입니다.",
  "site.home.quickApply.title": "빠른 참가 신청",
  "site.home.quickApply.desc": "대회를 선택한 뒤 참가 신청 탭에서 입금자명과 참가요건 동의 후 신청할 수 있습니다.",
  "site.home.quickApply.btnApply": "대회 선택하고 참가하기",
  "site.home.quickApply.btnLogin": "로그인",
  "site.home.location.title": "위치 안내",
  "site.home.location.subtitle": "당구장별 오시는 길은 당구장 소개에서 확인하세요.",
  "site.home.location.body": "대표 당구장의 주소와 지도는 각 당구장 상세 페이지에서 확인할 수 있습니다.",
  "site.home.location.hint": "당구장 소개 카드에서 원하는 구장을 선택해 주세요.",
  "site.footer.tagline": "캐롬클럽 · 당구장 홍보 · 대회 신청",
  "site.tournaments.title": "대회 목록",
  "site.tournaments.subtitle": "진행 예정 및 진행 중인 당구 대회입니다.",
  "site.tournaments.empty": "등록된 대회가 없습니다.",
  "site.tournaments.emptyHint": "곧 새로운 대회가 올라올 예정입니다.",
  "site.venues.title": "당구장 소개",
  "site.venues.subtitle": "제휴 당구장을 소개합니다.",
  "site.venues.empty": "등록된 당구장이 없습니다.",
  "site.community.billiardNotes.title": "난구노트",
  /** 커뮤니티 허브 상단 난구해결사 진입 카드(포스트 목록 슬롯만 있을 때 보조 블록) */
  "site.community.nanguPromo.title": "난구해결사",
  "site.community.nanguPromo.desc": "난구를 올리고 해법을 받아보세요",
  /** `PageSection` 링크가 없을 때 난구 카드 기본 경로 */
  "site.community.nanguPromo.href": "/community/nangu",
  /** 페이지 빌더 미리보기·슬롯 마커 */
  "site.pageBuilder.noticeOverlay.hint":
    "공지·팝업은 상단 ContentLayer에서 표시됩니다. 이 슬롯은 페이지 순서 마커입니다.",
  /** `{label}` 자리에 슬롯 한글 라벨 */
  "site.pageBuilder.slotFallback.template": "「{label}」슬롯 — 미리보기·데이터가 없어 자리만 표시합니다.",
  "site.pageBuilder.placeholder.quickMenu": "퀵 메뉴(홈 상단 메뉴는 별도 컴포넌트 — 2차 연동)",
  "site.pageBuilder.placeholder.homeCarousels": "홈 캐러셀(미연결 슬롯 — tournamentIntro·venueIntro 슬롯 사용)",
  "site.tournamentDetail.tabInfo": "대회 안내",
  "site.tournamentDetail.infoEmpty": "안내 내용이 없습니다.",
  // 대회/권역 용어 (관리자 메뉴·문구에서 변경 가능)
  "site.tournament.bracketSectionTitle": "대진 · 결과",
  "site.tournament.qualifierLabel": "권역 예선",
  "site.tournament.finalBracketLabel": "본선 대진표",
  "site.tournament.resultsLabel": "경기 결과",
  "site.tournament.stage.SETUP": "설정",
  "site.tournament.stage.QUALIFIER_RUNNING": "권역 예선 진행 중",
  "site.tournament.stage.QUALIFIER_COMPLETED": "권역 예선 완료",
  "site.tournament.stage.FINAL_READY": "본선 준비",
  "site.tournament.stage.FINAL_RUNNING": "본선 진행 중",
  "site.tournament.stage.COMPLETED": "종료",
  "site.tournament.finalLabel": "본선",
  "site.tournament.zonesEmpty": "권역이 없습니다.",
  "site.tournament.finalBracketView": "본선 대진표 보기",
  "site.tournament.finalBracketNotCreated": "본선 대진이 생성되지 않았습니다.",
  "site.tournament.finalBracketNotCreatedYet": "본선 대진이 아직 생성되지 않았습니다.",
  /** `{value}` 에 제한 기준(예: 0.8) */
  "site.tournament.apply.eligibilityUnderLine":
    "이 대회는 에버(avg) {value} 미만만 참가 신청할 수 있습니다.",
  "site.tournament.apply.eligibilityUnderFail": "이 대회는 {value} 미만만 신청할 수 있습니다.",
  "site.tournament.apply.certRequired": "이 대회는 인증파일 이미지 첨부가 필수입니다.",
  "site.tournament.apply.eligibilityNoAvg":
    "회원 프로필에 등록된 에버(avg)가 없어 참가 조건을 확인할 수 없습니다. 마이페이지에서 에버를 등록한 뒤 다시 시도해 주세요.",
  "site.tournament.apply.divisionAutoNotice": "신청 시 평균값 기준으로 부가 자동 배정됩니다.",

  "client.tournamentForm.sectionCert": "인증파일·참가 제한",
  "client.tournamentForm.certMode.label": "인증파일 요청",
  "client.tournamentForm.certMode.none": "요청 안 함",
  "client.tournamentForm.certMode.auto": "자동 확인(OCR)",
  "client.tournamentForm.certMode.manual": "수동 확인",
  "client.tournamentForm.manualReview.label": "운영 검토 필요",
  "client.tournamentForm.manualReview.hint":
    "켜 두면 인증·참가 자격 확인을 운영에서 검토합니다. (기본: 켜짐)",
  "client.tournamentForm.eligibility.label": "참가 제한(에버)",
  "client.tournamentForm.eligibility.none": "없음",
  "client.tournamentForm.eligibility.under": "미만",
  "client.tournamentForm.eligibility.valueLabel": "기준 에버 (미만)",
  "client.tournamentForm.eligibility.valuePlaceholder": "예: 0.8",
  "client.tournamentForm.division.enabled": "자동 부 분배 사용",
  "client.tournamentForm.division.metric.label": "부 배정 기준",
  "client.tournamentForm.division.metric.average": "AVERAGE",
  "client.tournamentForm.division.metric.score": "SCORE",
  "client.tournamentForm.division.add": "부 추가",
  "client.tournamentForm.division.namePlaceholder": "부 이름",
  "client.tournamentForm.division.minPlaceholder": "min",
  "client.tournamentForm.division.maxPlaceholder": "max",
  "client.tournamentForm.division.ruleHint": "판정 규칙: min <= avg < max",
  "client.tournamentForm.verificationGuide.label": "인증 안내 문구 (선택)",
  "client.tournamentForm.verificationGuide.placeholder":
    "예: 신청 시 선수증/성적표 이미지를 첨부해 주세요.",

  "client.operations.certificationMode.NONE": "없음",
  "client.operations.certificationMode.AUTO": "자동(OCR)",
  "client.operations.certificationMode.MANUAL": "수동",
  "client.operations.certOcr.pending": "대기",
  "client.operations.certOcr.success": "성공",
  "client.operations.certOcr.failed": "실패",
  "client.operations.certOcr.skipped": "미사용",
  "client.operations.certReview.pending": "검토대기",
  "client.operations.certReview.approved": "승인",
  "client.operations.certReview.rejected": "반려",
  "client.operations.certReview.sectionTitle": "인증·검토",
  "client.operations.certReview.approve": "인증 승인",
  "client.operations.certReview.reject": "인증 반려",
  "client.operations.participants.unassignedDivision": "미배정",
  "client.operations.participants.divisionCountFormat": "{name} ({count}명)",
  "client.operations.participants.sortByDivision": "부순",
  "client.operations.participants.sortByAverage": "average순",
  "client.operations.participants.sortByDefault": "기본순",

  // ----- 관리자 공통 (버튼·액션·테이블 등) -----
  "admin.common.back": "뒤로 가기",
  "admin.common.goToDashboard": "대시보드로 가기",
  "admin.common.save": "저장",
  "admin.common.saving": "저장중",
  "admin.common.saved": "저장되었습니다.",
  "admin.common.cancel": "취소",
  "admin.common.delete": "삭제",
  "admin.common.edit": "수정",
  "admin.common.add": "추가",
  "admin.common.remove": "제거",
  "admin.common.search": "검색",
  "admin.common.list": "목록",
  "admin.common.resetToDefault": "기본값으로 되돌리기",
  "admin.common.active": "활성",
  "admin.common.inactive": "비활성",
  "admin.common.actions": "동작",
  "admin.common.preview": "미리보기",
  "admin.common.type": "타입",
  "admin.common.title": "제목",
  "admin.common.content": "내용",
  "admin.common.findPlaceholder": "찾을 문자열",
  "admin.common.replacePlaceholder": "바꿀 문자열",
  "admin.common.bulkReplace": "일괄 변경",
  "admin.common.bulkReplaceRun": "치환 실행",
  "admin.common.logoutConfirm": "저장하지 않은 내용이 있습니다. 로그아웃하면 해당 내용은 유지되지 않습니다. 로그아웃하시겠습니까?",

  // ----- 플랫폼 관리자 목록/테이블 (공통) -----
  "admin.list.loading": "불러오는 중...",
  "admin.list.paginationPrev": "이전",
  "admin.list.paginationNext": "다음",
  "admin.list.emptyDash": "—",
  "admin.list.datePlaceholder": "-",
  "admin.list.filter.all": "전체",
  "admin.list.perPageLabel": "페이지당",
  "admin.list.perPageSuffix": "건",
  "admin.list.sortLabel": "정렬",
  "admin.list.thActions": "작업",
  "admin.list.thStatus": "상태",
  "admin.list.thType": "유형",
  "admin.list.thOrgName": "업체명",
  "admin.list.thVenue": "장소",
  "admin.list.thTournamentName": "대회명",
  "admin.list.thDateTime": "일시",
  "admin.list.emptyFiltered": "조건에 맞는 데이터가 없습니다.",
  "admin.list.searchAria": "목록 검색 및 필터",
  "admin.list.paginationNavAria": "페이지 이동",

  // ----- 플랫폼 관리자 대회 목록 (admin/tournaments) -----
  "admin.tournaments.pageTitlePlatform": "대회 현황",
  "admin.tournaments.pageTitleClient": "대회 목록",
  "admin.tournaments.btnLoadPrevious": "이전 대회 불러오기",
  "admin.tournaments.btnCreate": "대회 생성",
  "admin.tournaments.thHostClient": "주최 클라이언트",
  "admin.tournaments.thGameFormat": "경기방식",

  // ----- 플랫폼 관리자 커뮤니티 (admin/community/posts) -----
  "admin.community.posts.pageTitle": "커뮤니티 글 관리",
  "admin.community.posts.pageIntro": "커뮤니티 게시글을 조회·관리합니다.",
  "admin.community.posts.cardBody":
    "커뮤니티 게시글 목록은 커뮤니티 관리 화면에서 확인할 수 있습니다.",
  "admin.community.posts.linkCommunity": "커뮤니티로 이동",

  // ----- 플랫폼 관리자 정산·회비 장부 (admin/fee-ledger) -----
  "admin.feeLedger.pageTitle": "정산",
  "admin.feeLedger.pageIntro": "클라이언트 정산 관리 — 회비·납부 현황을 조회합니다.",
  "admin.feeLedger.summaryTotalOrgsLabel": "전체 업체",
  "admin.feeLedger.summaryPaidThisMonthLabel": "이번 달 납부",
  "admin.feeLedger.summaryArrearsOrgsLabel": "미납 업체",
  "admin.feeLedger.summaryTotalAmountLabel": "총 입금액",
  "admin.feeLedger.searchPlaceholder": "업체명·비고 검색",
  "admin.feeLedger.filterArrearsOnly": "미납만",
  "admin.feeLedger.sortName": "당구장순",
  "admin.feeLedger.sortStatus": "상태순",
  "admin.feeLedger.sortThisMonthStatus": "이번달 상태순",
  "admin.feeLedger.sortMonthsArrears": "미납개월순",
  "admin.feeLedger.sortLatestPaidAt": "최근 입금일순",
  "admin.feeLedger.sortTotalPaid": "총 입금순",
  "admin.feeLedger.sortFeeType": "회비유형순",
  "admin.feeLedger.sortAmount": "권장금액순",
  "admin.feeLedger.sortLatestPeriod": "최근 납부기간순",
  "admin.feeLedger.sortAdminRemarks": "비고순",
  "admin.feeLedger.sortDirAsc": "↑ 오름차순",
  "admin.feeLedger.sortDirDesc": "↓ 내림차순",
  "admin.feeLedger.btnExcel": "엑셀 다운로드",
  "admin.feeLedger.btnPaymentRegister": "입금 등록",
  "admin.feeLedger.tabLedger": "전체 장부",
  "admin.feeLedger.tabMonthly": "월별 장부 보기",
  "admin.feeLedger.tabPayments": "입금 내역",
  "admin.feeLedger.thBilliardHall": "당구장",
  "admin.feeLedger.thFeeType": "회비유형",
  "admin.feeLedger.thRecommendedAmount": "권장금액",
  "admin.feeLedger.thLatestPeriod": "최근 납부기간",
  "admin.feeLedger.thLatestPaidAt": "최근 입금일",
  "admin.feeLedger.thThisMonthStatus": "이번달 상태",
  "admin.feeLedger.thMonthsArrears": "미납개월",
  "admin.feeLedger.thTotalPaid": "총 입금",
  "admin.feeLedger.thRemarks": "비고",
  "admin.feeLedger.thDetail": "상세",
  "admin.feeLedger.rowOpenLedger": "회비 장부",
  "admin.feeLedger.monthlyBasisHint": "기준: {period} (월회비 업체만 표시)",
  "admin.feeLedger.paymentSelectTitle": "입금 등록 — 업체 선택",
  "admin.feeLedger.thPaymentDate": "입금일",
  "admin.feeLedger.thPaymentOrg": "업체",
  "admin.feeLedger.thPaymentPeriod": "기간",
  "admin.feeLedger.thPaymentAmount": "금액(원)",
  "admin.feeLedger.paymentsEmpty": "입금 내역이 없습니다.",
  "admin.feeLedger.paymentsLimitNote": "최근 {n}건만 표시됩니다.",
  "admin.feeLedger.feeType.MONTHLY": "월회비",
  "admin.feeLedger.feeType.ANNUAL": "연회비",

  // ----- 플랫폼 회원·권한 (admin/members) -----
  "admin.members.pageTitle": "회원·권한 관리",
  "admin.members.pageIntro":
    "회원/클라이언트/관리자를 검색·필터·정렬로 조회하고 권한 및 상태를 변경할 수 있습니다.",
  "admin.members.searchLabel": "검색 (이름·아이디·이메일)",
  "admin.members.searchPlaceholder": "이름, 아이디 또는 이메일",
  "admin.members.filterRoleTypeLabel": "구분",
  "admin.members.filterStatusLabel": "상태",
  "admin.members.sortCurrent": "현재: {sortBy} / {sortOrder}",
  "admin.members.quickPendingOnly": "승인대기만 보기",
  "admin.members.emptyFiltered": "조건에 맞는 회원이 없습니다. 검색·필터를 바꿔 보세요.",
  "admin.members.thName": "이름",
  "admin.members.thUsernameEmail": "아이디 / 이메일",
  "admin.members.thMemberCategory": "회원구분",
  "admin.members.thActivityScore": "활동 점수",
  "admin.members.thLevel": "LEVEL",
  "admin.members.thJoined": "가입일",
  "admin.members.thUpdated": "최근 수정일",
  "admin.members.thManage": "관리",
  "admin.members.btnManage": "관리",
  "admin.members.paginationSummary": "전체 {total}명 · {page} / {totalPages} 페이지",
  "admin.members.errorListLoad": "목록을 불러올 수 없습니다.",
  "admin.members.errorListQuery": "목록 조회 실패",
  "admin.members.errorRolesQuery": "레벨 조회 실패",
  "admin.members.errorPermissionsQuery": "권한 목록 조회 실패",
  "admin.members.errorPermissionsLoad": "권한 목록을 불러올 수 없습니다.",
  "admin.members.errorRankingQuery": "랭킹 조회 실패",
  "admin.members.rolesSectionTitle": "권한 역할 목록",
  "admin.members.rolesSectionHint": "권한을 볼 회원구분을 선택하세요.",
  "admin.members.roleCardMeta": "회원 {userCount}명 · 권한 {permCount}개",
  "admin.members.rolesEmpty": "권한 역할이 없습니다.",
  "admin.members.permissionTitleSuffix": " 권한",
  "admin.members.permissionTitleFallback": "권한 체크리스트",
  "admin.members.permissionSave": "권한 저장",
  "admin.members.permissionSaving": "저장 중...",
  "admin.members.permissionsLoading": "권한 목록을 불러오는 중...",
  "admin.members.permissionsEmpty": "권한이 없습니다.",
  "admin.members.permissionSaved": "권한이 저장되었습니다.",
  "admin.members.permissionSaveFailed": "권한 저장에 실패했습니다.",
  "admin.members.confirmAdminPermissionChange":
    "ADMIN 권한을 변경하면 관리자 기능에 직접 영향을 줄 수 있습니다. 계속하시겠습니까?",
  "admin.members.permCategory.community": "커뮤니티",
  "admin.members.permCategory.solver": "난구해결사",
  "admin.members.permCategory.note": "당구노트",
  "admin.members.permCategory.admin": "운영자",
  "admin.members.permCategory.other": "기타",
  "admin.members.rankingTitle": "해결사 랭킹",
  "admin.members.rankingSubtitle": "채택 수, GOOD 수, 해법 수, 활동 점수 기준 상위 10명",
  "admin.members.rankingLoading": "랭킹을 불러오는 중...",
  "admin.members.rankingEmpty": "랭킹이 없습니다.",
  "admin.members.rankingThRank": "순위",
  "admin.members.rankingThMember": "회원",
  "admin.members.rankingThRoles": "현재 ROLE / 추천 ROLE",
  "admin.members.rankingThSolutions": "해법 수",
  "admin.members.rankingThAccepted": "채택 수",
  "admin.members.rankingThGood": "GOOD 수",
  "admin.members.rankingThActivity": "활동 점수",
  "admin.members.modalTitle": "권한 · 상태 변경",
  "admin.members.modalChangeRbac": "변경할 RBAC 역할",
  "admin.members.modalRbacNone": "선택 안 함",
  "admin.members.modalManualLock": "관리자 수동 고정",
  "admin.members.modalRoleLabel": "구분 (권한)",
  "admin.members.modalStatusLabel": "상태",
  "admin.members.modalClientTier": "클라이언트 등급",
  "admin.members.modalApprovalStatus": "승인 상태",
  "admin.members.modalRecentPoints": "최근 활동 점수",
  "admin.members.modalPointsEmpty": "점수 이력이 없습니다.",
  "admin.members.modalPointsLoadFailed": "점수 이력을 불러올 수 없습니다.",
  "admin.members.modalPointsQueryFailed": "점수 이력 조회 실패",
  "admin.members.modalConfirmApply": "변경 내용을 적용하시겠습니까? 잘못 변경하면 서비스 이용에 영향을 줄 수 있습니다.",
  "admin.members.modalBtnConfirm": "변경 확인",
  "admin.members.patchSaveFailed": "저장에 실패했습니다.",
  "admin.members.patchSaveSuccess": "회원 레벨/상태가 저장되었습니다.",
  "admin.members.roleSaveFailed": "레벨 저장에 실패했습니다.",

  "admin.members.filter.roleType.user": "일반회원",
  "admin.members.filter.roleType.client_general": "일반 클라이언트",
  "admin.members.filter.roleType.client_registered": "등록 클라이언트(연회원)",
  "admin.members.filter.roleType.admin": "관리자",
  "admin.members.filter.status.active": "정상",
  "admin.members.filter.status.pending": "승인대기",
  "admin.members.filter.status.suspended": "정지",
  "admin.members.filter.status.withdrawn": "탈퇴",
  "admin.members.sortBy.createdAt": "날짜순",
  "admin.members.sortBy.name": "이름순",
  "admin.members.sortBy.role": "구분순",
  "admin.members.sortOrder.desc": "내림차순",
  "admin.members.sortOrder.asc": "오름차순",
  "admin.members.role.platformAdmin": "플랫폼 관리자",
  "admin.members.role.zoneManager": "권역 관리자",
  "admin.members.role.clientRegistered": "등록 클라이언트(연회원)",
  "admin.members.role.clientGeneral": "일반 클라이언트",
  "admin.members.role.user": "일반회원",
  "admin.members.status.withdrawn": "탈퇴",
  "admin.members.status.suspended": "정지",
  "admin.members.status.pendingApproval": "승인대기",
  "admin.members.status.active": "정상",
  "admin.members.display.nameFallback": "-",
  "admin.members.display.levelWithTier": "{level} ({tierName})",
  "admin.members.display.communityScoreTooltip": "communityScore {score}",
  "admin.members.modal.option.role.USER": "일반회원",
  "admin.members.modal.option.role.CLIENT_ADMIN": "일반 클라이언트 / 등록 클라이언트",
  "admin.members.modal.option.role.ZONE_MANAGER": "권역 관리자",
  "admin.members.modal.option.role.PLATFORM_ADMIN": "플랫폼 관리자",
  "admin.members.modal.option.memberStatus.ACTIVE": "정상",
  "admin.members.modal.option.memberStatus.SUSPENDED": "정지",
  "admin.members.modal.option.memberStatus.DELETED": "탈퇴",
  "admin.members.modal.option.orgClient.GENERAL": "일반 클라이언트",
  "admin.members.modal.option.orgClient.REGISTERED": "등록 클라이언트(연회원)",
  "admin.members.modal.option.orgApproval.PENDING": "승인대기",
  "admin.members.modal.option.orgApproval.APPROVED": "승인",
  "admin.members.modal.option.orgApproval.REJECTED": "반려",
  "admin.members.info.lineMemberCategory": "회원구분:",
  "admin.members.info.lineActivityScore": "활동 점수:",
  "admin.members.info.lineCommunityLevel": "커뮤니티 LEVEL:",
  "admin.members.info.lineCommunityScore": "communityScore:",

  // ----- 플랫폼 클라이언트 목록 (admin/venues) -----
  "admin.venues.pageTitle": "클라이언트 목록",
  "admin.venues.pageIntro":
    "승인된 클라이언트 목록입니다. 신규 등록은「신청 관리」에서 승인 처리하세요.",
  "admin.venues.filterTypeLabel": "클라이언트 종류",
  "admin.venues.filterTypeAria": "클라이언트 종류 필터",
  "admin.venues.thApplicationDate": "신청일",
  "admin.venues.thRegisteredDate": "등록일",
  "admin.venues.thSlug": "SLUG",
  "admin.venues.thRemarks": "비고",
  "admin.venues.empty": "등록된 클라이언트가 없습니다. 승인된 신청은 클라이언트 목록에 자동 등록됩니다.",
  "admin.venues.type.VENUE": "당구장",
  "admin.venues.type.CLUB": "동호회",
  "admin.venues.type.FEDERATION": "연맹",
  "admin.venues.type.INSTRUCTOR": "레슨",
  "admin.venues.status.ACTIVE": "정상",
  "admin.venues.status.SUSPENDED": "정지",
  "admin.venues.status.EXPELLED": "제명",
  "admin.venues.btnSuspend": "권한 정지",
  "admin.venues.btnRestore": "복원",
  "admin.venues.btnExpel": "제명",
  "admin.venues.confirmExpel": "제명하면 복원이 어렵습니다. 진행할까요?",
  "admin.venues.btnFeeLedger": "회비 장부",
  "admin.venues.remarksEditTitle": "클릭하여 편집",
  "admin.venues.alertPatchFailed": "저장에 실패했습니다.",
  "admin.venues.alertActionFailed": "처리에 실패했습니다.",

  // ----- 플랫폼 클라이언트 신청 (admin/client-applications) -----
  "admin.clientApplications.pageTitle": "클라이언트 신청",
  "admin.clientApplications.pageIntro": "당구장·동호회·연맹·주최자·강사 신청을 검토하고 승인/거절하세요.",
  "admin.clientApplications.pageIntroStrong":
    "승인 시 클라이언트(업체)가 새로 생성되고, 신청자 계정에 클라이언트 관리자 권한이 부여됩니다.",
  "admin.clientApplications.empty": "신청이 없습니다.",
  "admin.clientApplications.thRequestedType": "신청 유형",
  "admin.clientApplications.thApplicant": "신청자",
  "admin.clientApplications.thContact": "연락처",
  "admin.clientApplications.thCreated": "신청일",
  "admin.clientApplications.thRejectReason": "거절사유",
  "admin.clientApplications.thProcess": "처리",
  "admin.clientApplications.type.VENUE": "당구장",
  "admin.clientApplications.type.CLUB": "동호회",
  "admin.clientApplications.type.FEDERATION": "연맹/협회",
  "admin.clientApplications.type.HOST": "일반 주최자",
  "admin.clientApplications.type.INSTRUCTOR": "선수/강사/코치",
  "admin.clientApplications.status.PENDING": "대기",
  "admin.clientApplications.status.APPROVED": "승인",
  "admin.clientApplications.status.REJECTED": "반려",
  "admin.clientApplications.clientType.GENERAL": "일반업체",
  "admin.clientApplications.clientType.REGISTERED": "등록업체",
  "admin.clientApplications.btnApprove": "승인",
  "admin.clientApplications.btnReject": "거절",
  "admin.clientApplications.btnProcessing": "처리 중...",
  "admin.clientApplications.btnRevertToPending": "보류로 되돌리기",
  "admin.clientApplications.btnChangeToRejected": "거절로 변경",
  "admin.clientApplications.btnChangeToApproved": "승인으로 변경",
  "admin.clientApplications.btnEditRejectReason": "거절사유 수정",
  "admin.clientApplications.btnDeleteRejectReason": "거절사유 삭제",
  "admin.clientApplications.promptRejectOptional": "거절 사유 (선택, 취소 시 빈 값):",
  "admin.clientApplications.promptReject": "거절 사유 (선택):",
  "admin.clientApplications.promptEditReject": "거절사유 수정",
  "admin.clientApplications.confirmApproveRegistered":
    "등록업체로 승인하시겠습니까? 업체가 생성되고 연회원(ANNUAL)으로 설정됩니다.",
  "admin.clientApplications.confirmApproveGeneral":
    "이 신청을 승인하시겠습니까? 업체가 생성되고 신청자가 클라이언트 관리자로 변경됩니다.",
  "admin.clientApplications.confirmReject": "이 신청을 거절하시겠습니까?",
  "admin.clientApplications.confirmCancelApprovePending": "승인을 취소하고 대기(보류)로 되돌리시겠습니까?",
  "admin.clientApplications.confirmCancelApproveRejected": "승인을 취소하고 거절로 변경하시겠습니까?",
  "admin.clientApplications.confirmCancelRejectPending": "거절을 취소하고 대기(보류)로 되돌리시겠습니까?",
  "admin.clientApplications.confirmApproveFromRejectedRegistered":
    "등록업체로 승인하시겠습니까? 업체가 생성되고 연회원(ANNUAL)으로 설정됩니다.",
  "admin.clientApplications.confirmApproveFromRejectedGeneral":
    "이 신청을 승인하시겠습니까? 업체가 생성되고 신청자가 클라이언트 관리자로 변경됩니다.",
  "admin.clientApplications.confirmDeleteRejectReason": "거절사유를 삭제하시겠습니까?",
  "admin.clientApplications.errorListFetch": "목록을 불러올 수 없습니다.",
  "admin.clientApplications.errorListLoad": "목록을 불러오는 중 오류가 발생했습니다.",
  "admin.clientApplications.errorRefetch": "목록을 다시 불러오지 못했습니다.",
  "admin.clientApplications.errorActionFallback": "처리에 실패했습니다.",

  // ----- 플랫폼 문의 (admin/inquiries) -----
  "admin.inquiries.pageTitle": "문의관리",
  "admin.inquiries.pageIntro": "문의 목록 및 답변 관리입니다.",

  // ----- 클라이언트 대회 운영 허브 (목록·카드) -----
  "client.operations.eyebrow": "대회 운영",
  "client.operations.tournamentStatus.DRAFT": "임시저장",
  "client.operations.tournamentStatus.OPEN": "모집중",
  "client.operations.tournamentStatus.CLOSED": "마감",
  "client.operations.tournamentStatus.BRACKET_GENERATED": "대진 확정",
  "client.operations.tournamentStatus.FINISHED": "종료",
  "client.operations.tournamentStatus.HIDDEN": "숨김",
  "client.operations.participants.title": "참가 관리",
  "client.operations.participants.descriptionNoOrg": "먼저 업체를 선택·설정해 주세요.",
  "client.operations.participants.descriptionWithOrg": "「{orgName}」 대회별로 참가 승인·명단으로 이동합니다.",
  "client.operations.participants.setupCta": "업체 설정",
  "client.operations.participants.backToTournamentList": "대회 목록",
  "client.operations.participants.emptyNoTournaments": "등록된 대회가 없습니다. 대회 목록에서 새 대회를 만드세요.",
  "client.operations.participants.btnParticipantAdmin": "참가자 관리",
  "client.operations.tournamentRowMeta": "{date} · 확정 {confirmed}{maxSuffix}",
  "client.operations.mobile.confirmedLine": "확정 {confirmed}{maxSuffix}명",
  "client.operations.mobile.btnOpsConsole": "운영 콘솔",
  "client.operations.mobile.btnBracket": "대진표",
  "client.operations.mobile.linkRoster": "참가 명단 확정",
  "client.operations.mobile.linkBracketBuild": "대진 생성",
  "client.operations.mobile.linkTournamentInfo": "대회 정보",
  "client.operations.mobile.linkEditTournament": "대회 설정 수정",
  "client.operations.pageTitle": "대회 운영",
  "client.operations.pageDescriptionWithOrg": "조직 「{orgName}」 소속 대회만 표시됩니다.",
  "client.operations.linkPush": "푸시 발송",
  "client.operations.linkNewTournament": "새 대회",
  "client.operations.sectionTournaments": "등록된 대회",
  "client.operations.emptyTournaments": "등록된 대회가 없습니다.",
  "client.operations.thName": "대회명",
  "client.operations.thSchedule": "일정",
  "client.operations.thEntryFee": "참가비",
  "client.operations.thApplications": "신청",
  "client.operations.format.entryFee": "{amount}원",
  "client.operations.format.applicationsCell": "{confirmed}{maxSuffix}",
  "client.operations.quick.sectionTitle": "빠른 실행",
  "client.operations.quick.newTournament": "대회 생성",
  "client.operations.quick.participants": "신청자 관리",
  "client.operations.quick.noTournamentHint": "(대회 없음)",
  "client.operations.quick.bracketBuild": "대진 생성",
  "client.operations.quick.selectTournamentHint": "(대회 선택)",
  "client.operations.quick.bracketView": "대진표 보기",
  "client.operations.quick.push": "안내발송(푸시)",
  "client.operations.quick.featureFeedback": "기능 제안",
  "client.operations.quick.bugReport": "오류 신고",
  "client.operations.rowActions.menuSummary": "운영 메뉴 ▾",
  "client.feedback.feature.title": "기능 제안",
  "client.feedback.bug.title": "오류 신고",
  "client.feedback.submit": "제출하기",
  "client.feedback.success": "제출이 완료되었습니다.",
  "client.feedback.field.title": "제목",
  "client.feedback.field.content": "내용",
  "client.feedback.field.image": "첨부 이미지 (선택)",
  "client.feedback.field.pagePath": "발생 위치 (선택)",
  "client.feedback.placeholder.title": "제목을 입력해 주세요.",
  "client.feedback.placeholder.content": "상세 내용을 입력해 주세요.",
  "client.feedback.placeholder.imageUrl": "https://...",
  "client.feedback.placeholder.pagePath": "/client/operations",
  "client.settings.feedbackSectionTitle": "피드백",
  "client.settings.feedbackSectionDescription": "기능 제안과 오류 신고는 아래에서 제출할 수 있습니다.",
  "client.feedback.backToOperations": "운영 홈으로",
  "client.feedback.upload": "이미지 업로드",
  "client.feedback.uploading": "업로드중...",
  "client.feedback.submitting": "제출중...",

  // ----- 플랫폼 대시보드 -----
  "admin.dashboard.title": "플랫폼 운영 대시보드",
  "admin.dashboard.subtitle": "플랫폼 운영·모니터링용 대시보드입니다. 대회 실무(생성/수정/참가자/대진표)는 클라이언트 관리자(/client) 콘솔에서 진행합니다.",
  "admin.dashboard.quickLinks": "바로가기",
  "admin.dashboard.statClients": "클라이언트",
  "admin.dashboard.statPending": "승인 대기",
  "admin.dashboard.statTournaments": "전체 대회",
  "admin.dashboard.statInquiries": "문의",

  // ----- 설정 페이지별 제목·설명·라벨 -----
  "admin.settings.title": "설정",
  "admin.settings.pickItem": "설정 항목을 선택하세요.",
  "admin.settings.labels.title": "메뉴/문구",
  "admin.settings.labels.description": "사이트에 노출되는 메뉴명·버튼·안내 문구가 모두 아래에 표시됩니다. (회원이 입력한 게시글·댓글 등은 제외) 개별 수정(1개씩) 또는 일괄 변경 후 저장하면 반영됩니다.",
  "admin.settings.labels.searchLabel": "메뉴/문구 찾기",
  "admin.settings.labels.searchPlaceholder": "키 또는 문구로 검색 (예: 대회, 메뉴, hero)",
  "admin.settings.labels.bulkSectionTitle": "일괄 변경",
  "admin.settings.labels.bulkSectionDesc": "아래 표시된 문구 안에서만 찾아 바꿉니다. 검색으로 범위를 좁힌 뒤 적용하면 선택한 문구만 일괄 변경됩니다.",
  "admin.settings.labels.fixedTextLink": "고정 문구 관리",
  "admin.settings.labels.fixedTextNote": "에러 메시지·빈 화면 안내 등은",
  "admin.settings.labels.fixedTextNoteSuffix": "에서 수정할 수 있습니다.",
  "admin.settings.systemText.title": "고정 문구 관리",
  "admin.settings.systemText.groupLabel": "그룹",
  "admin.settings.systemText.searchLabel": "검색 (key / label / value)",
  "admin.settings.systemText.seedBtn": "기본 키 시드",
  "admin.settings.systemText.resetAllBtn": "전체 기본값 초기화",
  "admin.settings.systemText.bulkSectionTitle": "단어 전체 치환",
  "admin.settings.notices.title": "공지 관리",
  "admin.settings.notices.typeBar": "공지바",
  "admin.settings.notices.typePopup": "팝업",
  "admin.settings.notices.typeEmergency": "긴급 공지",
  "admin.settings.notices.addBtn": "공지 추가",
  "admin.settings.notices.editTitle": "공지 수정",
  "admin.settings.notices.exposurePeriod": "노출 기간",
  "admin.settings.notices.mobile": "모바일",
  "admin.settings.features.title": "기능 관리",
  "admin.settings.backup.title": "데이터 백업",
  "admin.settings.backup.runBtn": "백업 실행",
  "admin.settings.backup.running": "백업 실행 중…",
  "admin.settings.backup.listTitle": "백업 목록",
  "admin.settings.backup.filename": "파일명",
  "admin.settings.backup.size": "크기",
  "admin.settings.backup.createdAt": "생성일시",
  "admin.settings.backup.restoreTitle": "복원 안내",
  "admin.settings.backup.cronTitle": "일일 자동 백업",
  "admin.settings.system.title": "시스템 관리",
  "admin.settings.system.pathRevalidate": "경로 재검증",
  "admin.settings.system.revalidatePathBtn": "해당 경로만 재검증",
  "admin.settings.system.clearCacheBtn": "전체 주요 경로 캐시 초기화",
  "admin.settings.site.title": "사이트 설정",
  "admin.settings.site.logoLabel": "사이트 로고",
  "admin.settings.site.logoPreviewAlt": "로고 미리보기",
  "admin.settings.site.chooseImage": "이미지 선택",
  "admin.settings.site.chooseAnotherImage": "다른 이미지 선택",
  "admin.settings.integration.title": "연동 설정",
  "admin.settings.integration.currentStatus": "현재 설정 상태",
  "admin.settings.integration.configured": "설정됨",
  "admin.settings.integration.notConfigured": "미설정",
  "admin.settings.notifications.title": "알림 설정",
  "admin.settings.footer.title": "푸터 설정",
  "admin.settings.footer.useFooter": "푸터 사용",
  "admin.settings.footer.bgColor": "배경색",
  "admin.settings.footer.textColor": "글자색",
  "admin.settings.footer.sponsorTitle": "주관사 정보",
  "admin.settings.footer.partnersTitle": "협력업체",
  "admin.settings.footer.addPartner": "추가",
  "admin.settings.footer.partnerNamePlaceholder": "업체명",
  "admin.settings.featured.title": "추천 콘텐츠 관리",
  "admin.settings.featured.addSectionTitle": "추천 추가",
  "admin.settings.featured.typeTournament": "대회",
  "admin.settings.featured.typeVenue": "당구장",
  "admin.settings.featured.typePost": "게시글",
  "admin.settings.billing.title": "요금 정책",
  "admin.settings.billing.enableTitle": "요금 정책 활성화",
  "admin.settings.header.title": "헤더 설정",
  "admin.settings.header.bgColor": "헤더 배경색",
  "admin.settings.header.textColor": "헤더 글자색",
  "admin.settings.header.activeColor": "활성 메뉴 강조색",
  "admin.participants.title": "참가자 관리",
  "admin.participants.clientOnlyTitle": "참가자 관리는 클라이언트 관리자 전용입니다",
  "admin.participants.backToTournaments": "대회 현황",
  "admin.tournament.newSave": "새 대회 저장",
  "admin.tournament.copyFromPrevious": "이전 대회를 복사해 날짜·장소 등만 수정해 새 대회로 등록할 수 있습니다.",
  "admin.tournament.venueNameReadonly": "당구장명 (수정 불가)",
  "admin.tournament.addressReadonly": "주소 (수정 불가)",
  "admin.tournament.addVenue": "대회 당구장 (개최 장소로 추가)",
  "admin.tournament.selectVenuePlaceholder": "당구장 선택 후 추가",
  "admin.tournament.bracketSettings": "대진표 설정",
  "admin.tournament.entrySettings": "참가 설정",
  "admin.tournament.prizeSettings": "상금 설정",
  "admin.clientOnly.title": "클라이언트 관리자 전용",
  "admin.clientOnly.message": "이 기능은 대회를 운영하는 클라이언트 관리자 전용입니다. 플랫폼 관리자는 대회 생성·수정·참가자·대진표 관리를 할 수 없습니다.",
  "admin.forbidden.title": "캐롬클럽 관리자 권한이 없습니다",
  "admin.forbidden.notAdmin": "이 계정은 관리자가 아닙니다.",
  "admin.forbidden.loginHint": "관리자 전용 계정(아이디: admin)으로 로그인하세요. 계정이 없다면 터미널에서 npx prisma db seed를 실행한 뒤 비밀번호 admin1234로 로그인하세요.",
  "admin.forbidden.logoutHint": "지금 로그인된 계정을 로그아웃한 뒤 admin으로 다시 로그인하세요.",
  "admin.forbidden.logoutAndLoginBtn": "로그아웃 후 관리자로 로그인",
  "admin.forbidden.goHome": "메인으로 이동",

  // ----- 클라이언트 대시보드 -----
  "client.dashboard.title": "대회 운영 대시보드",
  "client.dashboard.label": "대시보드",
  "client.dashboard.goTo": "대시보드로",
  "client.dashboard.loginPrompt": "클라이언트 대시보드는 로그인 후 이용할 수 있습니다.",
  "client.dashboard.consoleTitle": "대회 운영 콘솔",
  /** 콘솔 상단 헤더 — 사이트 메인(/) 이동 */
  "client.console.homeButton": "홈",
  "client.zones.title": "부/권역 설정",
  "client.zones.description": "대회별 권역 연결은 각 대회 상세 → 부/권역 탭에서 설정할 수 있습니다. 권역별 예선·본선 운영 시 사용합니다.",
  "client.sidebar.dashboard": "대시보드",
  "client.sidebar.myTournaments": "내 대회",
  "client.sidebar.participants": "참가자 관리",
  "client.sidebar.zones": "부/권역 설정",
  "client.sidebar.brackets": "대진표 관리",
  "client.sidebar.results": "결과 관리",
  "client.sidebar.coAdmins": "공동관리자 관리",
  "client.sidebar.promo": "홍보/페이지 관리",
  "client.sidebar.setup": "조직 설정",
  "client.sidebar.billing": "이용 현황",
  "client.sidebar.myZones": "내가 맡은 권역",
  "client.sidebar.zoneOps": "권역 운영",

  /** 플랫폼 관리자 대시보드 홈 */
  "admin.dashboard.siteHomeAria": "사이트 홈으로 이동",

  /** 클라이언트 콘솔 게이트(레이아웃) */
  "client.gate.loginRequiredTitle": "로그인이 필요합니다",
  "client.gate.loginButton": "로그인",
  "client.gate.noClientRoleTitle": "클라이언트 권한이 없습니다",
  "client.gate.noClientRoleBody":
    "당구장·동호회·연맹·주최자·강사로 등록하시려면 마이페이지에서 클라이언트 등록 신청을 해 주세요.",
  "client.gate.goMypage": "마이페이지로",

  /** 클라이언트 콘솔 — 사이드/헤더/하단 (라벨·제목·aria) */
  "client.console.menuSection": "메뉴",
  "client.console.siteMainTitle": "사이트 메인으로",
  "client.console.nav.dash": "관리자홈",
  "client.console.nav.org": "내 정보/사업장 관리",
  "client.console.nav.tournament": "전체대회",
  "client.console.nav.promo": "콘텐츠/홍보",
  "client.console.nav.billing": "전체정산",
  "client.console.nav.settings": "설정",
  "client.console.title.dash": "운영 대시보드",
  "client.console.title.org": "내 정보/사업장 관리",
  "client.console.title.operations": "대회 운영",
  "client.console.title.tournamentInfo": "대회 정보",
  "client.console.title.billingPlatform": "플랫폼 이용",
  "client.console.title.billing": "정산",
  "client.console.title.settings": "설정",
  "client.console.title.promo": "콘텐츠/홍보",
  "client.console.title.schedule": "일정 / 예약",
  "client.console.title.zones": "부/권역",
  "client.console.title.coAdmins": "공동관리자",
  "client.console.title.fallback": "클라이언트 콘솔",
  "client.console.bottomNav.aria": "클라이언트 콘솔 하단 메뉴",
  "client.console.bottomNav.home": "관리자홈",
  "client.console.bottomNav.tournaments": "전체대회",
  "client.console.bottomNav.entries": "참가",
  "client.console.bottomNav.billing": "전체정산",
  "client.console.bottomNav.settings": "설정",

  /** 클라이언트 운영 대시보드 홈 (`/client/dashboard`) */
  "client.dashboard.home.eyebrow": "업무 시작",
  "client.dashboard.home.pageHeaderTitle": "운영 대시보드",
  "client.dashboard.home.descriptionWithOrg":
    "「{name}」 — 모집·대진·정산까지 한 화면에서 상태를 확인하고 바로 이동합니다.",
  "client.dashboard.home.descriptionNoOrg": "조직이 연결되면 운영 지표가 표시됩니다.",
  "client.dashboard.home.noOrgTitle": "소속된 업체가 없습니다.",
  "client.dashboard.home.noOrgLine2Prefix": "클라이언트 신청이 플랫폼 관리자에게 승인되면 업체가 생성됩니다. ",
  "client.dashboard.home.noOrgMypageLink": "마이페이지",
  "client.dashboard.home.noOrgLine2Suffix": "에서 신청 상태를 확인하세요.",
  "client.dashboard.home.sectionOpsSummary": "운영 현황 요약",
  "client.dashboard.home.thMetric": "지표",
  "client.dashboard.home.thValue": "값",
  "client.dashboard.home.thGo": "이동",
  "client.dashboard.home.metricActiveTournaments": "진행·모집 중 대회 (종료 제외)",
  "client.dashboard.home.metricPendingApprovals": "참가 승인 대기",
  "client.dashboard.home.metricBracketIncomplete": "명단 확정 후 대진 미생성",
  "client.dashboard.home.metricSettlementPending": "종료 대회 정산 미완료",
  "client.dashboard.home.linkTournamentOps": "대회 운영",
  "client.dashboard.home.linkBracketConsole": "대진 콘솔",
  "client.dashboard.home.linkSettlement": "정산",
  "client.dashboard.home.sectionToday": "오늘 일정 (KST)",
  "client.dashboard.home.todayEmpty": "오늘 시작하는 대회나 예정된 본선 경기가 없습니다.",
  "client.dashboard.home.todayTournamentsHeader": "대회 시작일이 오늘",
  "client.dashboard.home.todayMatchesHeader": "본선 경기 (예정 시각 오늘)",
  "client.dashboard.home.linkBracket": "브래킷",
  "client.dashboard.home.matchTimeTbd": "시간 미정",
  "client.dashboard.home.sectionPending": "대기 작업",
  "client.dashboard.home.pendingEmpty": "즉시 처리할 큐가 없습니다.",
  "client.dashboard.home.pendingAction": "처리",
  "client.dashboard.home.sectionQuick": "빠른 작업",
  "client.dashboard.home.quickNewTournament": "새 대회",
  "client.dashboard.home.quickApprove": "참가 승인",
  "client.dashboard.home.quickTournamentOps": "대회 운영",
  "client.dashboard.home.quickBracket": "대진·브래킷",
  "client.dashboard.home.quickSettlement": "정산",
  "client.dashboard.home.quickPromo": "홍보",
  "client.dashboard.home.sectionRecent": "최근 활동",
  "client.dashboard.home.recentTournamentsHeader": "대회 정보 갱신",
  "client.dashboard.home.recentEmpty": "기록이 없습니다.",
  "client.dashboard.home.thTournament": "대회",
  "client.dashboard.home.thUpdated": "갱신",
  "client.dashboard.home.open": "열기",
  "client.dashboard.home.auditHeader": "본선 경기 감사 로그",
  "client.dashboard.home.auditEmpty": "최근 기록이 없습니다.",
  "client.dashboard.home.sectionAlerts": "알림 · 주의",
  "client.dashboard.home.alertsEmpty": "표시할 경고가 없습니다.",
  "client.dashboard.home.orgLabelPrefix": "업체:",
  "client.dashboard.home.orgRegisteredAnnual": "등록업체 (연회원)",
  "client.dashboard.home.orgRegistered": "등록업체",
  "client.dashboard.home.orgGeneral": "일반업체",
  "client.dashboard.home.orgPendingApproval": "승인 대기",
  "client.dashboard.home.footerHelpMid": " — 도움말은 ",
  "client.dashboard.home.footerHelpPromo": "콘텐츠/홍보",
  "client.dashboard.home.footerHelpSep": " · ",
  "client.dashboard.home.footerHelpSettings": "설정",

  "client.dashboard.tournamentStatus.DRAFT": "초안",
  "client.dashboard.tournamentStatus.OPEN": "모집중",
  "client.dashboard.tournamentStatus.CLOSED": "마감",
  "client.dashboard.tournamentStatus.BRACKET_GENERATED": "대진확정",
  "client.dashboard.tournamentStatus.FINISHED": "종료",
  "client.dashboard.tournamentStatus.HIDDEN": "숨김",
  "client.dashboard.matchStatus.PENDING": "대기",
  "client.dashboard.matchStatus.READY": "준비",
  "client.dashboard.matchStatus.BYE": "부전",
  "client.dashboard.matchStatus.IN_PROGRESS": "진행",
  "client.dashboard.matchStatus.COMPLETED": "완료",
};

export type AdminCopyKey = keyof typeof DEFAULT_ADMIN_COPY;

/** 특정 키 값만 (키 없음·빈 문자열이면 기본값) */
export function getCopyValue(copy: Record<string, string>, key: AdminCopyKey): string {
  const raw = copy[key];
  if (typeof raw === "string" && raw.trim() !== "") return raw;
  return DEFAULT_ADMIN_COPY[key] ?? String(key);
}

/** `{name}` 형태 플레이스홀더 치환 (문구 설정에서 숫자·날짜 등을 넣을 때) */
export function fillAdminCopyTemplate(template: string, vars: Record<string, string | number>): string {
  let s = template;
  for (const [k, v] of Object.entries(vars)) {
    s = s.split(`{${k}}`).join(String(v));
  }
  return s;
}

/** 클라이언트 대회 운영 허브의 `Tournament.status` 표시 라벨 */
export function getClientOperationsTournamentStatus(copy: Record<string, string>, status: string): string {
  const k = `client.operations.tournamentStatus.${status}` as AdminCopyKey;
  if (k in DEFAULT_ADMIN_COPY) return getCopyValue(copy, k);
  return status;
}

/** 대시보드·관리자 목록 공통 `Tournament.status` 라벨 (`client.dashboard.tournamentStatus.*`) */
export function getDashboardTournamentStatusLabel(copy: Record<string, string>, status: string): string {
  const k = `client.dashboard.tournamentStatus.${status}` as AdminCopyKey;
  if (k in DEFAULT_ADMIN_COPY) return getCopyValue(copy, k);
  return status;
}

/** 클라이언트 목록·정산 등 업체 상태 (`admin.venues.status.*`) */
export function getVenueOrgStatusLabel(copy: Record<string, string>, status: string): string {
  const k = `admin.venues.status.${status}` as AdminCopyKey;
  if (k in DEFAULT_ADMIN_COPY) return getCopyValue(copy, k);
  return status;
}

/** 정산 장부 회비 유형 (`admin.feeLedger.feeType.*`) */
export function getFeeLedgerFeeTypeLabel(copy: Record<string, string>, feeType: string): string {
  const k = `admin.feeLedger.feeType.${feeType}` as AdminCopyKey;
  if (k in DEFAULT_ADMIN_COPY) return getCopyValue(copy, k);
  return feeType;
}

/** 설정 페이지에서 그룹별 키 목록 */
export const ADMIN_COPY_GROUPS: { group: string; keys: (keyof typeof DEFAULT_ADMIN_COPY)[] }[] = [
  { group: "사이드 메뉴", keys: ["menu.home", "menu.dashboard", "menu.tournaments", "menu.participants", "menu.brackets", "menu.members", "menu.inquiries", "menu.venues", "menu.venueList", "menu.clientApplications", "menu.settings"] },
  { group: "상단 유저 메뉴", keys: ["nav.myInfo", "nav.settings", "nav.home", "nav.logout"] },
  { group: "공통", keys: ["app.title", "footer.copyright"] },
  { group: "설정 하위 메뉴", keys: ["settings.menu.site", "settings.menu.notifications", "settings.menu.integration", "settings.menu.labels"] },
  {
    group: "사이트 안내/설명",
    keys: [
      "site.home.tournaments.title", "site.home.tournaments.subtitle", "site.home.tournaments.subtitleEmpty",
      "site.home.tournaments.empty", "site.home.tournaments.btnList", "site.home.tournaments.btnViewAll", "site.home.tournaments.btnJoin",
      "site.home.tournaments.nearbyLoading", "site.home.tournaments.nearbyFind",
      "site.home.tournaments.nearbyErrorGeolocation", "site.home.tournaments.nearbyErrorFetch", "site.home.tournaments.nearbyErrorPermission",
      "site.home.venues.title", "site.home.venues.subtitle", "site.home.venues.subtitleWithList",
      "site.home.venues.empty", "site.home.venues.linkVenueListCta", "site.home.venues.manualTitleFallback",
      "site.home.venues.emptyFiltered", "site.home.venues.filterAria",
      "site.home.venues.categoryAll", "site.home.venues.categoryDaedae", "site.home.venues.categoryMixed",
      "site.home.venues.carouselPrev", "site.home.venues.carouselNext", "site.home.venues.carouselPageAria",
      "site.home.venues.btnViewAll",
      "site.home.community.notes.title", "site.home.community.notes.desc",
      "site.home.community.nangu.title", "site.home.community.nangu.desc",
      "site.home.quickApply.title", "site.home.quickApply.desc", "site.home.quickApply.btnApply", "site.home.quickApply.btnLogin",
      "site.home.location.title", "site.home.location.subtitle", "site.home.location.body", "site.home.location.hint",
      "site.footer.tagline",
      "site.tournaments.title", "site.tournaments.subtitle", "site.tournaments.empty", "site.tournaments.emptyHint",
      "site.venues.title", "site.venues.subtitle", "site.venues.empty",
      "site.community.billiardNotes.title",
      "site.community.nanguPromo.title", "site.community.nanguPromo.desc", "site.community.nanguPromo.href",
      "site.pageBuilder.noticeOverlay.hint",
      "site.pageBuilder.slotFallback.template",
      "site.pageBuilder.placeholder.quickMenu",
      "site.pageBuilder.placeholder.homeCarousels",
      "site.tournamentDetail.tabInfo", "site.tournamentDetail.infoEmpty",
    ],
  },
  {
    group: "대회/권역 용어",
    keys: [
      "site.tournament.bracketSectionTitle", "site.tournament.qualifierLabel", "site.tournament.finalBracketLabel", "site.tournament.resultsLabel",
      "site.tournament.finalLabel", "site.tournament.zonesEmpty", "site.tournament.finalBracketView",
      "site.tournament.finalBracketNotCreated", "site.tournament.finalBracketNotCreatedYet",
      "site.tournament.stage.SETUP", "site.tournament.stage.QUALIFIER_RUNNING", "site.tournament.stage.QUALIFIER_COMPLETED",
      "site.tournament.stage.FINAL_READY", "site.tournament.stage.FINAL_RUNNING", "site.tournament.stage.COMPLETED",
      "site.tournament.apply.eligibilityUnderLine", "site.tournament.apply.eligibilityUnderFail", "site.tournament.apply.certRequired",
      "site.tournament.apply.eligibilityNoAvg", "site.tournament.apply.divisionAutoNotice",
    ],
  },
  {
    group: "클라이언트 대회 폼·인증 검토",
    keys: [
      "client.tournamentForm.sectionCert", "client.tournamentForm.certMode.label", "client.tournamentForm.certMode.none",
      "client.tournamentForm.certMode.auto", "client.tournamentForm.certMode.manual", "client.tournamentForm.manualReview.label",
      "client.tournamentForm.manualReview.hint", "client.tournamentForm.eligibility.label", "client.tournamentForm.eligibility.none",
      "client.tournamentForm.eligibility.under", "client.tournamentForm.eligibility.valueLabel", "client.tournamentForm.eligibility.valuePlaceholder",
      "client.tournamentForm.division.enabled", "client.tournamentForm.division.metric.label",
      "client.tournamentForm.division.metric.average", "client.tournamentForm.division.metric.score",
      "client.tournamentForm.division.add", "client.tournamentForm.division.namePlaceholder",
      "client.tournamentForm.division.minPlaceholder", "client.tournamentForm.division.maxPlaceholder", "client.tournamentForm.division.ruleHint",
      "client.tournamentForm.verificationGuide.label", "client.tournamentForm.verificationGuide.placeholder",
      "client.operations.certificationMode.NONE", "client.operations.certificationMode.AUTO", "client.operations.certificationMode.MANUAL",
      "client.operations.certOcr.pending", "client.operations.certOcr.success", "client.operations.certOcr.failed", "client.operations.certOcr.skipped",
      "client.operations.certReview.pending", "client.operations.certReview.approved", "client.operations.certReview.rejected",
      "client.operations.certReview.sectionTitle", "client.operations.certReview.approve", "client.operations.certReview.reject",
      "client.operations.participants.unassignedDivision", "client.operations.participants.divisionCountFormat",
      "client.operations.participants.sortByDivision", "client.operations.participants.sortByAverage",
      "client.operations.participants.sortByDefault",
    ],
  },
  {
    group: "관리자 공통 (버튼·액션)",
    keys: [
      "admin.common.back", "admin.common.goToDashboard", "admin.common.save", "admin.common.saving", "admin.common.saved",
      "admin.common.cancel", "admin.common.delete", "admin.common.edit", "admin.common.add", "admin.common.remove",
      "admin.common.search", "admin.common.list", "admin.common.resetToDefault", "admin.common.active", "admin.common.inactive",
      "admin.common.actions", "admin.common.preview", "admin.common.type", "admin.common.title", "admin.common.content",
      "admin.common.findPlaceholder", "admin.common.replacePlaceholder", "admin.common.bulkReplace", "admin.common.bulkReplaceRun",
      "admin.common.logoutConfirm",
      "admin.list.loading",
      "admin.list.paginationPrev",
      "admin.list.paginationNext",
      "admin.list.emptyDash",
      "admin.list.datePlaceholder",
      "admin.list.filter.all",
      "admin.list.perPageLabel",
      "admin.list.perPageSuffix",
      "admin.list.sortLabel",
      "admin.list.thActions",
      "admin.list.thStatus",
      "admin.list.thType",
      "admin.list.thOrgName",
      "admin.list.thVenue",
      "admin.list.thTournamentName",
      "admin.list.thDateTime",
      "admin.list.emptyFiltered",
      "admin.list.searchAria",
      "admin.list.paginationNavAria",
    ],
  },
  {
    group: "플랫폼 클라이언트 목록 (venues)",
    keys: [
      "admin.venues.pageTitle",
      "admin.venues.pageIntro",
      "admin.venues.filterTypeLabel",
      "admin.venues.filterTypeAria",
      "admin.venues.thApplicationDate",
      "admin.venues.thRegisteredDate",
      "admin.venues.thSlug",
      "admin.venues.thRemarks",
      "admin.venues.empty",
      "admin.venues.type.VENUE",
      "admin.venues.type.CLUB",
      "admin.venues.type.FEDERATION",
      "admin.venues.type.INSTRUCTOR",
      "admin.venues.status.ACTIVE",
      "admin.venues.status.SUSPENDED",
      "admin.venues.status.EXPELLED",
      "admin.venues.btnSuspend",
      "admin.venues.btnRestore",
      "admin.venues.btnExpel",
      "admin.venues.confirmExpel",
      "admin.venues.btnFeeLedger",
      "admin.venues.remarksEditTitle",
      "admin.venues.alertPatchFailed",
      "admin.venues.alertActionFailed",
    ],
  },
  {
    group: "플랫폼 클라이언트 신청",
    keys: [
      "admin.clientApplications.pageTitle",
      "admin.clientApplications.pageIntro",
      "admin.clientApplications.pageIntroStrong",
      "admin.clientApplications.empty",
      "admin.clientApplications.thRequestedType",
      "admin.clientApplications.thApplicant",
      "admin.clientApplications.thContact",
      "admin.clientApplications.thCreated",
      "admin.clientApplications.thRejectReason",
      "admin.clientApplications.thProcess",
      "admin.clientApplications.type.VENUE",
      "admin.clientApplications.type.CLUB",
      "admin.clientApplications.type.FEDERATION",
      "admin.clientApplications.type.HOST",
      "admin.clientApplications.type.INSTRUCTOR",
      "admin.clientApplications.status.PENDING",
      "admin.clientApplications.status.APPROVED",
      "admin.clientApplications.status.REJECTED",
      "admin.clientApplications.clientType.GENERAL",
      "admin.clientApplications.clientType.REGISTERED",
      "admin.clientApplications.btnApprove",
      "admin.clientApplications.btnReject",
      "admin.clientApplications.btnProcessing",
      "admin.clientApplications.btnRevertToPending",
      "admin.clientApplications.btnChangeToRejected",
      "admin.clientApplications.btnChangeToApproved",
      "admin.clientApplications.btnEditRejectReason",
      "admin.clientApplications.btnDeleteRejectReason",
      "admin.clientApplications.promptRejectOptional",
      "admin.clientApplications.promptReject",
      "admin.clientApplications.promptEditReject",
      "admin.clientApplications.confirmApproveRegistered",
      "admin.clientApplications.confirmApproveGeneral",
      "admin.clientApplications.confirmReject",
      "admin.clientApplications.confirmCancelApprovePending",
      "admin.clientApplications.confirmCancelApproveRejected",
      "admin.clientApplications.confirmCancelRejectPending",
      "admin.clientApplications.confirmApproveFromRejectedRegistered",
      "admin.clientApplications.confirmApproveFromRejectedGeneral",
      "admin.clientApplications.confirmDeleteRejectReason",
      "admin.clientApplications.errorListFetch",
      "admin.clientApplications.errorListLoad",
      "admin.clientApplications.errorRefetch",
      "admin.clientApplications.errorActionFallback",
    ],
  },
  {
    group: "플랫폼 문의",
    keys: ["admin.inquiries.pageTitle", "admin.inquiries.pageIntro"],
  },
  {
    group: "플랫폼 관리자 대회·커뮤니티·정산",
    keys: [
      "admin.tournaments.pageTitlePlatform",
      "admin.tournaments.pageTitleClient",
      "admin.tournaments.btnLoadPrevious",
      "admin.tournaments.btnCreate",
      "admin.tournaments.thHostClient",
      "admin.tournaments.thGameFormat",
      "admin.community.posts.pageTitle",
      "admin.community.posts.pageIntro",
      "admin.community.posts.cardBody",
      "admin.community.posts.linkCommunity",
      "admin.feeLedger.pageTitle",
      "admin.feeLedger.pageIntro",
      "admin.feeLedger.summaryTotalOrgsLabel",
      "admin.feeLedger.summaryPaidThisMonthLabel",
      "admin.feeLedger.summaryArrearsOrgsLabel",
      "admin.feeLedger.summaryTotalAmountLabel",
      "admin.feeLedger.searchPlaceholder",
      "admin.feeLedger.filterArrearsOnly",
      "admin.feeLedger.sortName",
      "admin.feeLedger.sortStatus",
      "admin.feeLedger.sortThisMonthStatus",
      "admin.feeLedger.sortMonthsArrears",
      "admin.feeLedger.sortLatestPaidAt",
      "admin.feeLedger.sortTotalPaid",
      "admin.feeLedger.sortFeeType",
      "admin.feeLedger.sortAmount",
      "admin.feeLedger.sortLatestPeriod",
      "admin.feeLedger.sortAdminRemarks",
      "admin.feeLedger.sortDirAsc",
      "admin.feeLedger.sortDirDesc",
      "admin.feeLedger.btnExcel",
      "admin.feeLedger.btnPaymentRegister",
      "admin.feeLedger.tabLedger",
      "admin.feeLedger.tabMonthly",
      "admin.feeLedger.tabPayments",
      "admin.feeLedger.thBilliardHall",
      "admin.feeLedger.thFeeType",
      "admin.feeLedger.thRecommendedAmount",
      "admin.feeLedger.thLatestPeriod",
      "admin.feeLedger.thLatestPaidAt",
      "admin.feeLedger.thThisMonthStatus",
      "admin.feeLedger.thMonthsArrears",
      "admin.feeLedger.thTotalPaid",
      "admin.feeLedger.thRemarks",
      "admin.feeLedger.thDetail",
      "admin.feeLedger.rowOpenLedger",
      "admin.feeLedger.monthlyBasisHint",
      "admin.feeLedger.paymentSelectTitle",
      "admin.feeLedger.thPaymentDate",
      "admin.feeLedger.thPaymentOrg",
      "admin.feeLedger.thPaymentPeriod",
      "admin.feeLedger.thPaymentAmount",
      "admin.feeLedger.paymentsEmpty",
      "admin.feeLedger.paymentsLimitNote",
      "admin.feeLedger.feeType.MONTHLY",
      "admin.feeLedger.feeType.ANNUAL",
    ],
  },
  {
    group: "플랫폼 회원·권한 (목록)",
    keys: [
      "admin.members.pageTitle", "admin.members.pageIntro",
      "admin.members.searchLabel", "admin.members.searchPlaceholder",
      "admin.members.filterRoleTypeLabel", "admin.members.filterStatusLabel",
      "admin.members.sortCurrent", "admin.members.quickPendingOnly",
      "admin.members.emptyFiltered",
      "admin.members.thName", "admin.members.thUsernameEmail", "admin.members.thMemberCategory",
      "admin.members.thActivityScore", "admin.members.thLevel",
      "admin.members.thJoined", "admin.members.thUpdated", "admin.members.thManage",
      "admin.members.btnManage", "admin.members.paginationSummary",
      "admin.members.errorListLoad", "admin.members.errorListQuery", "admin.members.errorRolesQuery",
      "admin.members.errorPermissionsQuery", "admin.members.errorPermissionsLoad", "admin.members.errorRankingQuery",
      "admin.members.rolesSectionTitle", "admin.members.rolesSectionHint", "admin.members.roleCardMeta", "admin.members.rolesEmpty",
      "admin.members.permissionTitleSuffix", "admin.members.permissionTitleFallback",
      "admin.members.permissionSave", "admin.members.permissionSaving", "admin.members.permissionsLoading", "admin.members.permissionsEmpty",
      "admin.members.permissionSaved", "admin.members.permissionSaveFailed", "admin.members.confirmAdminPermissionChange",
      "admin.members.permCategory.community", "admin.members.permCategory.solver", "admin.members.permCategory.note",
      "admin.members.permCategory.admin", "admin.members.permCategory.other",
      "admin.members.rankingTitle", "admin.members.rankingSubtitle", "admin.members.rankingLoading", "admin.members.rankingEmpty",
      "admin.members.rankingThRank", "admin.members.rankingThMember", "admin.members.rankingThRoles",
      "admin.members.rankingThSolutions", "admin.members.rankingThAccepted", "admin.members.rankingThGood", "admin.members.rankingThActivity",
      "admin.members.modalTitle", "admin.members.modalChangeRbac", "admin.members.modalRbacNone", "admin.members.modalManualLock",
      "admin.members.modalRoleLabel", "admin.members.modalStatusLabel", "admin.members.modalClientTier", "admin.members.modalApprovalStatus",
      "admin.members.modalRecentPoints", "admin.members.modalPointsEmpty", "admin.members.modalPointsLoadFailed", "admin.members.modalPointsQueryFailed",
      "admin.members.modalConfirmApply", "admin.members.modalBtnConfirm",
      "admin.members.patchSaveFailed", "admin.members.patchSaveSuccess", "admin.members.roleSaveFailed",
      "admin.members.filter.roleType.user", "admin.members.filter.roleType.client_general",
      "admin.members.filter.roleType.client_registered", "admin.members.filter.roleType.admin",
      "admin.members.filter.status.active", "admin.members.filter.status.pending",
      "admin.members.filter.status.suspended", "admin.members.filter.status.withdrawn",
      "admin.members.sortBy.createdAt", "admin.members.sortBy.name", "admin.members.sortBy.role",
      "admin.members.sortOrder.desc", "admin.members.sortOrder.asc",
      "admin.members.role.platformAdmin", "admin.members.role.zoneManager", "admin.members.role.clientRegistered",
      "admin.members.role.clientGeneral", "admin.members.role.user",
      "admin.members.status.withdrawn", "admin.members.status.suspended", "admin.members.status.pendingApproval", "admin.members.status.active",
      "admin.members.display.nameFallback", "admin.members.display.levelWithTier", "admin.members.display.communityScoreTooltip",
      "admin.members.modal.option.role.USER", "admin.members.modal.option.role.CLIENT_ADMIN", "admin.members.modal.option.role.ZONE_MANAGER",
      "admin.members.modal.option.role.PLATFORM_ADMIN",
      "admin.members.modal.option.memberStatus.ACTIVE", "admin.members.modal.option.memberStatus.SUSPENDED", "admin.members.modal.option.memberStatus.DELETED",
      "admin.members.modal.option.orgClient.GENERAL", "admin.members.modal.option.orgClient.REGISTERED",
      "admin.members.modal.option.orgApproval.PENDING", "admin.members.modal.option.orgApproval.APPROVED", "admin.members.modal.option.orgApproval.REJECTED",
      "admin.members.info.lineMemberCategory", "admin.members.info.lineActivityScore", "admin.members.info.lineCommunityLevel", "admin.members.info.lineCommunityScore",
    ],
  },
  {
    group: "클라이언트 대회 운영 (목록·카드)",
    keys: [
      "client.operations.eyebrow",
      "client.operations.tournamentStatus.DRAFT", "client.operations.tournamentStatus.OPEN", "client.operations.tournamentStatus.CLOSED",
      "client.operations.tournamentStatus.BRACKET_GENERATED", "client.operations.tournamentStatus.FINISHED", "client.operations.tournamentStatus.HIDDEN",
      "client.operations.participants.title", "client.operations.participants.descriptionNoOrg", "client.operations.participants.descriptionWithOrg",
      "client.operations.participants.setupCta", "client.operations.participants.backToTournamentList", "client.operations.participants.emptyNoTournaments",
      "client.operations.participants.btnParticipantAdmin",
      "client.operations.tournamentRowMeta", "client.operations.mobile.confirmedLine",
      "client.operations.mobile.btnOpsConsole", "client.operations.mobile.btnBracket",
      "client.operations.mobile.linkRoster", "client.operations.mobile.linkBracketBuild", "client.operations.mobile.linkTournamentInfo",
      "client.operations.mobile.linkEditTournament",
      "client.operations.pageTitle", "client.operations.pageDescriptionWithOrg", "client.operations.linkPush", "client.operations.linkNewTournament",
      "client.operations.sectionTournaments", "client.operations.emptyTournaments",
      "client.operations.thName", "client.operations.thSchedule", "client.operations.thEntryFee",
      "client.operations.thApplications",
      "client.operations.format.entryFee", "client.operations.format.applicationsCell",
      "client.operations.quick.sectionTitle", "client.operations.quick.newTournament", "client.operations.quick.participants",
      "client.operations.quick.noTournamentHint", "client.operations.quick.bracketBuild", "client.operations.quick.selectTournamentHint",
      "client.operations.quick.bracketView", "client.operations.quick.push", "client.operations.quick.featureFeedback",
      "client.operations.quick.bugReport", "client.operations.rowActions.menuSummary",
      "client.feedback.feature.title", "client.feedback.bug.title", "client.feedback.submit", "client.feedback.success",
      "client.feedback.field.title", "client.feedback.field.content", "client.feedback.field.image", "client.feedback.field.pagePath",
      "client.feedback.placeholder.title", "client.feedback.placeholder.content", "client.feedback.placeholder.imageUrl", "client.feedback.placeholder.pagePath",
      "client.settings.feedbackSectionTitle", "client.settings.feedbackSectionDescription",
      "client.feedback.backToOperations", "client.feedback.upload", "client.feedback.uploading", "client.feedback.submitting",
    ],
  },
  {
    group: "플랫폼 대시보드",
    keys: [
      "admin.dashboard.title", "admin.dashboard.subtitle", "admin.dashboard.quickLinks",
      "admin.dashboard.statClients", "admin.dashboard.statPending", "admin.dashboard.statTournaments", "admin.dashboard.statInquiries",
      "admin.dashboard.siteHomeAria",
    ],
  },
  {
    group: "설정 페이지별",
    keys: [
      "admin.settings.title", "admin.settings.pickItem",
      "admin.settings.labels.title", "admin.settings.labels.description", "admin.settings.labels.searchLabel", "admin.settings.labels.searchPlaceholder",
      "admin.settings.labels.bulkSectionTitle", "admin.settings.labels.bulkSectionDesc", "admin.settings.labels.fixedTextLink", "admin.settings.labels.fixedTextNote", "admin.settings.labels.fixedTextNoteSuffix",
      "admin.settings.systemText.title", "admin.settings.systemText.groupLabel", "admin.settings.systemText.searchLabel", "admin.settings.systemText.seedBtn", "admin.settings.systemText.resetAllBtn", "admin.settings.systemText.bulkSectionTitle",
      "admin.settings.notices.title", "admin.settings.notices.typeBar", "admin.settings.notices.typePopup", "admin.settings.notices.typeEmergency", "admin.settings.notices.addBtn", "admin.settings.notices.editTitle", "admin.settings.notices.exposurePeriod", "admin.settings.notices.mobile",
      "admin.settings.features.title", "admin.settings.backup.title", "admin.settings.backup.runBtn", "admin.settings.backup.running", "admin.settings.backup.listTitle", "admin.settings.backup.filename", "admin.settings.backup.size", "admin.settings.backup.createdAt", "admin.settings.backup.restoreTitle", "admin.settings.backup.cronTitle",
      "admin.settings.system.title", "admin.settings.system.pathRevalidate", "admin.settings.system.revalidatePathBtn", "admin.settings.system.clearCacheBtn",
      "admin.settings.site.title", "admin.settings.site.logoLabel", "admin.settings.site.logoPreviewAlt", "admin.settings.site.chooseImage", "admin.settings.site.chooseAnotherImage",
      "admin.settings.integration.title", "admin.settings.integration.currentStatus", "admin.settings.integration.configured", "admin.settings.integration.notConfigured",
      "admin.settings.notifications.title", "admin.settings.footer.title", "admin.settings.footer.useFooter", "admin.settings.footer.bgColor", "admin.settings.footer.textColor", "admin.settings.footer.sponsorTitle", "admin.settings.footer.partnersTitle", "admin.settings.footer.addPartner", "admin.settings.footer.partnerNamePlaceholder",
      "admin.settings.featured.title", "admin.settings.featured.addSectionTitle", "admin.settings.featured.typeTournament", "admin.settings.featured.typeVenue", "admin.settings.featured.typePost",
      "admin.settings.billing.title", "admin.settings.billing.enableTitle", "admin.settings.header.title", "admin.settings.header.bgColor", "admin.settings.header.textColor", "admin.settings.header.activeColor",
    ],
  },
  {
    group: "참가자·대회·클라이언트 전용 안내",
    keys: [
      "admin.participants.title", "admin.participants.clientOnlyTitle", "admin.participants.backToTournaments",
      "admin.tournament.newSave", "admin.tournament.copyFromPrevious", "admin.tournament.venueNameReadonly", "admin.tournament.addressReadonly", "admin.tournament.addVenue", "admin.tournament.selectVenuePlaceholder",
      "admin.tournament.bracketSettings", "admin.tournament.entrySettings", "admin.tournament.prizeSettings",
      "admin.clientOnly.title", "admin.clientOnly.message", "admin.forbidden.title", "admin.forbidden.notAdmin", "admin.forbidden.loginHint", "admin.forbidden.logoutHint", "admin.forbidden.logoutAndLoginBtn", "admin.forbidden.goHome",
    ],
  },
  {
    group: "클라이언트 대시보드",
    keys: [
      "client.dashboard.title", "client.dashboard.label", "client.dashboard.goTo", "client.dashboard.loginPrompt", "client.dashboard.consoleTitle", "client.console.homeButton",
      "client.zones.title", "client.zones.description",
      "client.sidebar.dashboard", "client.sidebar.myTournaments", "client.sidebar.participants", "client.sidebar.zones", "client.sidebar.brackets", "client.sidebar.results", "client.sidebar.coAdmins", "client.sidebar.promo", "client.sidebar.setup", "client.sidebar.billing", "client.sidebar.myZones", "client.sidebar.zoneOps",
      "client.gate.loginRequiredTitle", "client.gate.loginButton", "client.gate.noClientRoleTitle", "client.gate.noClientRoleBody", "client.gate.goMypage",
      "client.console.menuSection", "client.console.siteMainTitle",
      "client.console.nav.dash", "client.console.nav.org", "client.console.nav.tournament", "client.console.nav.promo", "client.console.nav.billing", "client.console.nav.settings",
      "client.console.title.dash", "client.console.title.org", "client.console.title.operations", "client.console.title.tournamentInfo",
      "client.console.title.billingPlatform", "client.console.title.billing", "client.console.title.settings", "client.console.title.promo",
      "client.console.title.schedule", "client.console.title.zones", "client.console.title.coAdmins", "client.console.title.fallback",
      "client.console.bottomNav.aria", "client.console.bottomNav.home", "client.console.bottomNav.tournaments", "client.console.bottomNav.entries", "client.console.bottomNav.billing", "client.console.bottomNav.settings",
      "client.dashboard.home.eyebrow", "client.dashboard.home.pageHeaderTitle", "client.dashboard.home.descriptionWithOrg", "client.dashboard.home.descriptionNoOrg",
      "client.dashboard.home.noOrgTitle", "client.dashboard.home.noOrgLine2Prefix", "client.dashboard.home.noOrgMypageLink", "client.dashboard.home.noOrgLine2Suffix",
      "client.dashboard.home.sectionOpsSummary", "client.dashboard.home.thMetric", "client.dashboard.home.thValue", "client.dashboard.home.thGo",
      "client.dashboard.home.metricActiveTournaments", "client.dashboard.home.metricPendingApprovals", "client.dashboard.home.metricBracketIncomplete", "client.dashboard.home.metricSettlementPending",
      "client.dashboard.home.linkTournamentOps", "client.dashboard.home.linkBracketConsole", "client.dashboard.home.linkSettlement",
      "client.dashboard.home.sectionToday", "client.dashboard.home.todayEmpty", "client.dashboard.home.todayTournamentsHeader", "client.dashboard.home.todayMatchesHeader",
      "client.dashboard.home.linkBracket", "client.dashboard.home.matchTimeTbd",
      "client.dashboard.home.sectionPending", "client.dashboard.home.pendingEmpty", "client.dashboard.home.pendingAction",
      "client.dashboard.home.sectionQuick", "client.dashboard.home.quickNewTournament", "client.dashboard.home.quickApprove", "client.dashboard.home.quickTournamentOps",
      "client.dashboard.home.quickBracket", "client.dashboard.home.quickSettlement", "client.dashboard.home.quickPromo",
      "client.dashboard.home.sectionRecent", "client.dashboard.home.recentTournamentsHeader", "client.dashboard.home.recentEmpty",
      "client.dashboard.home.thTournament", "client.dashboard.home.thUpdated", "client.dashboard.home.open",
      "client.dashboard.home.auditHeader", "client.dashboard.home.auditEmpty",
      "client.dashboard.home.sectionAlerts", "client.dashboard.home.alertsEmpty",
      "client.dashboard.home.orgLabelPrefix", "client.dashboard.home.orgRegisteredAnnual", "client.dashboard.home.orgRegistered", "client.dashboard.home.orgGeneral", "client.dashboard.home.orgPendingApproval",
      "client.dashboard.home.footerHelpMid", "client.dashboard.home.footerHelpPromo", "client.dashboard.home.footerHelpSep", "client.dashboard.home.footerHelpSettings",
      "client.dashboard.tournamentStatus.DRAFT", "client.dashboard.tournamentStatus.OPEN", "client.dashboard.tournamentStatus.CLOSED",
      "client.dashboard.tournamentStatus.BRACKET_GENERATED", "client.dashboard.tournamentStatus.FINISHED", "client.dashboard.tournamentStatus.HIDDEN",
      "client.dashboard.matchStatus.PENDING", "client.dashboard.matchStatus.READY", "client.dashboard.matchStatus.BYE",
      "client.dashboard.matchStatus.IN_PROGRESS", "client.dashboard.matchStatus.COMPLETED",
    ],
  },
];
